-- vim.api.nvim_set_hl(0, 'NvimTreeFolderName', { fg = "#d1d5db" })
vim.api.nvim_set_hl(0, 'NvimTreeNormal', { fg = "#e5e5e5" })
vim.api.nvim_set_hl(0, 'NvimTreeNormalNC', { fg = "#e5e5e5" })
vim.api.nvim_set_hl(0, 'NvimTreeGitDirty', { fg = "#86e1fc" })
-- vim.api.nvim_set_hl(0, 'NvimTreeGitStaged', {  })
-- vim.api.nvim_set_hl(0, 'NvimTreeOpenedFolderName', { underline = true, bold = true })
-- vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextError', { fg = "#c53b53" })
-- vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextWarn', { link = "Yellow" })
-- vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextInfo', { link = "Green" })
-- vim.api.nvim_set_hl(0, 'DiagnosticVirtualTextHint', { link = "Blue" })
vim.api.nvim_set_hl(0, 'MatchParen', { bg = "blue" })
-- vim.api.nvim_set_hl(0, '@keyword', { italic = true, fg = "#fb4934" }) -- gruvbox
-- vim.api.nvim_set_hl(0, '@punctuation.bracket', { fg = "#a89984" }) -- gruvbox
vim.api.nvim_set_hl(0, '@tag.attribute', { italic = true })
-- vim.api.nvim_set_hl(0, '@keyword.return', { link = "Keyword" })
-- vim.api.nvim_set_hl(0, '@tag.delimiter', { fg = "#f0f0f0" })
vim.api.nvim_set_hl(0, 'IndentBlanklineContextChar', { fg = "#b39df3" })
vim.api.nvim_set_hl(0, 'IlluminatedWordRead', { underline = true })
vim.api.nvim_set_hl(0, 'IlluminatedWordText', { underline = true })
vim.api.nvim_set_hl(0, 'IlluminatedWordWrite', { underline = true })
-- vim.api.nvim_set_hl(0, 'Hlargs', { fg = "#ff966c", italic = true })
